/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Note } from "./library/models";
export namespace Components {
    interface AppRoot {
    }
    interface MonoEditor {
        "content": string;
    }
    interface MonoOrganizer {
        "notes": Note[];
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLMonoEditorElement extends Components.MonoEditor, HTMLStencilElement {
    }
    var HTMLMonoEditorElement: {
        prototype: HTMLMonoEditorElement;
        new (): HTMLMonoEditorElement;
    };
    interface HTMLMonoOrganizerElement extends Components.MonoOrganizer, HTMLStencilElement {
    }
    var HTMLMonoOrganizerElement: {
        prototype: HTMLMonoOrganizerElement;
        new (): HTMLMonoOrganizerElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "mono-editor": HTMLMonoEditorElement;
        "mono-organizer": HTMLMonoOrganizerElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface MonoEditor {
        "content"?: string;
        "onContentChanged"?: (event: CustomEvent<string>) => void;
    }
    interface MonoOrganizer {
        "notes"?: Note[];
        "onNoteCreate"?: (event: CustomEvent<void>) => void;
        "onNoteLoad"?: (event: CustomEvent<string>) => void;
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "mono-editor": MonoEditor;
        "mono-organizer": MonoOrganizer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "mono-editor": LocalJSX.MonoEditor & JSXBase.HTMLAttributes<HTMLMonoEditorElement>;
            "mono-organizer": LocalJSX.MonoOrganizer & JSXBase.HTMLAttributes<HTMLMonoOrganizerElement>;
        }
    }
}
